src/teachadvisor/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from home.views import HomeView, AboutUsView, PromotionView, ContactView, TermsAndConditionView, DisclaimerView, PrivacyPolicyView, RefundPolicyView, FAQTutorView, FAQStudentView, CSupportView, TutorialsView, CareersView, PressView, PartnershipsView, SiteMapView, Test
from home.charts import StudentChart, TeacherChart

from teacher.views import TeacherCreate, TeacherUpdate, TeacherList, TeacherDetail, FavTeacherList
from opening.views import OpeningCreate, OpeningList, OpeningUpdate, OpeningDetail, FavOpeningList, POpeningList, POpeningListInactive
from student.views import StudentCreate, StudentUpdate, StudentList, StudentDetail
from messaging.views import PostMessageView, MessageDetailView, OpeningSelectMsg, Oselectmsgc, Oselectmsgw, BlockSub
from messaging.views import MessageListViewAll, MessageListViewMsg, MessageListViewPpl, MessageListViewWip, MessageListViewDon
from tags.views import FavTeacherSub, FavOpeningSub
from orders.views import Accept, AcceptConf, OrderDetail, OrderDetailView, Withdraw, WithConf, OpeningConfirmAppOff, AppOffConf#, OpeningConfirmRej, RejectMsg
from orderreview.views import OrderCancelReview, OrderCompleteReview, Finish, RecordMsg, ReviewListView, ReviewDetailView, ReviewList, OrderCompleteConfirm, ReviewDetail#, AddCredits, CheckOut, CheckOutFinal, Invoice
from billing.views import ImageSub, FeatureSub, AnalyticsSub, StudentBISub, StripeAddCredits, StripePayment, StripeCheckOut, StripeInvoice
from notifications.views import allin, read, get_notifications_ajax, MsgCountView

from examdownload.views.confirm import ConfirmTemplateView
from examdownload.views.download import DownloadView
from examdownload.views.subject_list import SubjectsListTemplateView

from blog.views import post_list, post_detail



                    
from django.conf.urls import url
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from blog.models import BlogPost
from home.sitemaps import BlogSitemap, StaticViewSitemap
from django.views.generic import TemplateView







urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^accounts/',include('allauth.urls')),
    url(r'^$', HomeView.as_view(), name='Home'),
    url(r'^contact/$', ContactView.as_view(), name='Contact'),
    url(r'^promotions/$', PromotionView.as_view(), name='Promotions'),

    url(r'^termsandconditions/$', TermsAndConditionView.as_view(), name='TermsAndCondition'),
    url(r'^disclaimer/$', DisclaimerView.as_view(), name='Disclaimer'),
    url(r'^privacypolicy/$', PrivacyPolicyView.as_view(), name='PrivacyPolicy'),
    url(r'^refundpolicy/$', RefundPolicyView.as_view(), name='RefundPolicy'),

    url(r'^FAQTutors/$', FAQTutorView.as_view(), name='FAQTutor'),
    url(r'^FAQStudents/$', FAQStudentView.as_view(), name='FAQStudent'),
    url(r'^customersupport/$', CSupportView.as_view(), name='Customer_Support'),
    url(r'^tutorials/$', TutorialsView.as_view(), name='Tutorials'),

    url(r'^aboutus/$', AboutUsView.as_view(), name='AboutUs'),
    url(r'^careers/$', CareersView.as_view(), name='Careers'),
    url(r'^press/$', PressView.as_view(), name='Press'),
    url(r'^partnership/$', PartnershipsView.as_view(), name='Partnership'),


    url(r'^site-map/$', SiteMapView.as_view()),

    # url(r'^creditadd/$', payment_form, name='NewAddCredits'),
    # url(r"^checkout$", checkout, name="checkout_page"),
    # url(r"^checkoutdone$", checkoutfinish, name="checkoutdone"),








    # url(r'^prelims/$', PrelimsView.as_view(), name='Prelims'),

    url(r'^blog/$', post_list, name='blog_list'),
    url(r'^blog/(?P<slug>[\w-]+)/$', post_detail, name='blog_detail'),


    #
    # exams downloaders (examdownload)
    #
    url(r'^prelims(?:/+)?$',SubjectsListTemplateView.as_view(),name='examdownload_subjects_list'),
    url(r'^downloadexam/confirm(?:/+)?(?:\?+)?$',ConfirmTemplateView.as_view(),name='examdownload_confirm'),
    url(r'^downloadexam/' + r'([a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12})' + r'(?:/+)?$', DownloadView.as_view(), name='examdownload_download'),



    url(r'^test/$', Test, name='Test'),

    #billing and subscription
    url(r'^billing/imagesub/$', ImageSub.as_view(), name='ImageSub'),
    url(r'^billing/analyticssub/$', AnalyticsSub.as_view(), name='AnalyticsSub'),
    url(r'^billing/studentbisub/$', StudentBISub.as_view(), name='StudentBISub'),
    url(r'^billing/featuresub/$', FeatureSub.as_view(), name='FeatureSub'),

    url(r'^creditadd/$', StripeAddCredits.as_view(), name='NewAddCredits'),
    url(r"^payment$", StripePayment.as_view(), name="StripePayment"),
    url(r"^checkout$", StripeCheckOut.as_view(), name="StripeCheckOut"),
    url(r"^invoice$", StripeInvoice.as_view(), name="StripeInvoice"),




    # url(r'^billing/creditadd/$', AddCredits.as_view(), name='AddCredits'),
    # url(r'^billing/checkout/$', CheckOut.as_view(), name='CheckOut'),
    # url(r'^billing/checkout/final$', CheckOutFinal.as_view(), name='CheckOutFinal'),
    # url(r'^billing/checkout/invoice$', Invoice.as_view(), name='Invoice'),
    # url(r'^billing/subscription/$', ImageSub.as_view(), name='ImageSub'),

    #worker details
    url(r'^tutor/add/$', TeacherCreate.as_view(), name='TeacherCreate'),
    url(r'^tutor/$', TeacherList.as_view(), name='TeacherList'),
    url(r'^tutor/(?P<pk>[0-9]+)/edit$', TeacherUpdate.as_view(), name='TeacherUpdate'),
    url(r'^tutor/(?P<pk>[0-9]+)/$', TeacherDetail.as_view(), name='TeacherDetail'),

    #company details
    url(r'^student/add/$', StudentCreate.as_view(), name='StudentCreate'),
    url(r'^student/$', StudentList.as_view(), name='StudentList'), #to block when live
    url(r'^student/(?P<pk>[0-9]+)/edit$', StudentUpdate.as_view(), name='StudentUpdate'),
    url(r'^student/(?P<pk>[0-9]+)/$', StudentDetail.as_view(), name='StudentDetail'),

    #openings
    url(r'^opening/add/$', OpeningCreate.as_view(), name='OpeningCreate'),
    url(r'^opening/$', OpeningList.as_view(), name='OpeningList'),
    url(r'^opening/(?P<pk>[0-9]+)/edit$', OpeningUpdate.as_view(), name='OpeningUpdate'),
    url(r'^opening/(?P<pk>[0-9]+)/$', OpeningDetail.as_view(), name='OpeningDetail'),
    
    #openings that are specific to a company
    url(r'^popenings/$', POpeningList.as_view(), name='POpeningList'),
    url(r'^popeningsinact/$', POpeningListInactive.as_view(), name='POpeningListInactive'),

    #messaging
    url(r'^messaging/$', PostMessageView.as_view(), name='Messaging'),
    url(r'^messagelistall/$', MessageListViewAll.as_view(), name='MessageListViewAll'),
    url(r'^messagelistmsg/$', MessageListViewMsg.as_view(), name='MessageListViewMsg'),
    url(r'^messagelistppl/$', MessageListViewPpl.as_view(), name='MessageListViewPpl'),
    url(r'^messagelistwip/$', MessageListViewWip.as_view(), name='MessageListViewWip'),
    url(r'^messagelistdon/$', MessageListViewDon.as_view(), name='MessageListViewDon'),


    url(r'^messagedetail/(?P<pk>[0-9]+)/$', MessageDetailView.as_view(), name='MessageDetail'),

    #favoriting openings or teacher
    url(r'^tutor/(?P<pk>[0-9]+)/FavTeacherSub$', FavTeacherSub),
    url(r'^opening/(?P<pk>[0-9]+)/FavOpeningSub$', FavOpeningSub),

    #favorite lists
    url(r'^tutor/favteacherlist$', FavTeacherList.as_view(), name='FavTeacherList'),
    url(r'^opening/favopeninglist$', FavOpeningList.as_view(), name='FavOpeningList'),

    #selecting opening to message for student
    url(r'^openingselectmsg/$', OpeningSelectMsg.as_view(), name='OpeningSelectMsg'),
    url(r'^openingselectmsg/Oselectmsgc$', Oselectmsgc, name='Oselectmsgc'),

    #selecting opening to message for teacher
    url(r'^opening/(?P<pk>[0-9]+)/Oselectmsgw$',Oselectmsgw),
    url(r'^messagedetail/(?P<pk>[0-9]+)/appoffconf$', AppOffConf, name='AppOffConf'),
    url(r'^opening/appoffconfirm$', OpeningConfirmAppOff.as_view(), name='OpeningConfirmAppOff'),

    #get acceptance
    url(r'^messagedetail/(?P<pk>[0-9]+)/accconf$', AcceptConf, name='AcceptConf'),
    url(r'^messagedetail/Accept$',Accept.as_view(), name='Accept'),

    #withdraw proposal
    url(r'^messagedetail/(?P<pk>[0-9]+)/withconf$', WithConf, name='WithConf'),
    url(r'^opening/withdraw$', Withdraw.as_view(), name='Withdraw'),
    
    #block and unblock users
    url(r'^messagedetail/(?P<pk>[0-9]+)/blocksub$', BlockSub, name='BlockSub'),


    #viewing orders
    # url(r'^order/$', OrderListView.as_view(), name='OrderList'),
    url(r'^order/detail/$', OrderDetail, name='OrderDetail'),
    url(r'^order/detail/view$', OrderDetailView.as_view(), name='OrderDetailView'),

    #finish orders
    url(r'^order/finish$', Finish, name='Finish'),
    url(r'^order/completeconfirm$', OrderCompleteConfirm.as_view(), name='OrderCompleteConfirm'),

    #completed or cancelled and ready for review    
    url(r'^review/recordmsg$', RecordMsg, name='RecordMsg'),
    url(r'^review/cancelreview/$', OrderCancelReview.as_view(), name='OrderCancelReview'),
    url(r'^review/completereview/$', OrderCompleteReview.as_view(), name='OrderCompleteReview'),

    #viewing reviews
    url(r'^review/reviewlist$', ReviewList, name='ReviewList'),
    url(r'^review/reviewlist/view$', ReviewListView.as_view(), name='ReviewListView'),
    
    url(r'^review/reviewdetail/$', ReviewDetail, name='ReviewDetail'),
    url(r'^review/reviewdetail/view$', ReviewDetailView.as_view(), name='ReviewDetailView'),

    #notifications
    url(r'^notifications/$', allin, name='notifications_all'),
    url(r'^notifications/ajax/$', get_notifications_ajax, name='get_notifications_ajax'),
    url(r'^notifications/(?P<id>\d+)/$', read, name='notifications_read'),
    url(r'^notifications/count/$', MsgCountView.as_view(), name='msg_count'),

    # url(r'^examplepiechart/$', ExamplePieChart.as_view(), name='ExamplePieChart'),

src/orderreview/models.py
from __future__ import unicode_literals
from variables.models import Country, Subject_Expertise, Level_Expertise, Educational_Level, Education, Region, Education_School, Expertise_Type
from student.models import Student
from opening.models import Opening
from teacher.models import Teacher
from messaging.models import Message
from orders.models import Order
from django.db import models
from django.db.models.signals import pre_save, post_save
from django.urls import reverse
import datetime


class ReviewTeacher(models.Model):
	teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
	student = models.ForeignKey(Student, on_delete=models.CASCADE)
	opening = models.ForeignKey(Opening, on_delete=models.CASCADE)
	message = models.ForeignKey(Message, on_delete=models.CASCADE)
	order = models.ForeignKey(Order, on_delete=models.CASCADE)

	subject = models.ForeignKey(Subject_Expertise, on_delete=models.CASCADE, null=True, blank=True)
	level = models.ForeignKey(Level_Expertise, on_delete=models.CASCADE, null=True, blank=True)
	group_tuition = models.BooleanField(default=False)
	price = models.IntegerField(null=True, blank=True)
	datebetween = models.IntegerField(null=True, blank=True)

	cnc = models.CharField(max_length=20, blank=True, null=True)
	reason = models.CharField(max_length=120, null=True, blank=True)
	comments = models.TextField(max_length=500,null=True, blank=True)
	score = models.IntegerField(null=True, blank=True)
	
	gradebefore = models.CharField(max_length=20, null=True, blank=True)
	gradeafter = models.CharField(max_length=20, null=True, blank=True)
	review = models.TextField(max_length=500,null=True, blank=True)
	reviewcomment = models.TextField(max_length=500,null=True, blank=True)
	anonymous = models.BooleanField(default=False)
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)


	def __str__(self):
		return str(self.teacher)


	def get_teacher_url(self):
		teacher_id = self.teacher.id
		return reverse('TeacherDetail', kwargs={'pk': teacher_id})

	def get_message_url(self):
		msg = Message.objects.filter(senduser=self.student.user , touser=self.teacher.user , re_opening=self.opening).first()
		return reverse('MessageDetail', kwargs={'pk': msg.id})

	def get_grade(self):
		scorevariance = "From " + str(self.gradebefore) + " to " + str(self.gradeafter)
		return scorevariance

	def get_rscore(self):
		score = self.score
		if score is not None:
			score = round(score,1)
		else:
			score = 0.0
		return score



grade_choices = (
		('100-95', '100-95'),
		('94-90', '94-90'),
		('89-85', '89-85'),
		('84-80', '84-80'),
		('79-75', '79-75'),
		('74-70', '74-70'),
		('69-65', '69-65'),
		('64-60', '64-60'),
		('59-55', '59-55'),
		('54-50', '54-50'),
		('49-45', '49-45'),
		('45-40', '45-40'),
		('0-39', '0-39'),
	)


def update_review(sender, instance, *args, **kwargs):
	#to collect the number of days between opening create and review to identify possibility of fake reviews

	todate = datetime.datetime.now().date()
	# todate = todate.replace(tzinfo=None)
	# todate = todate.date()
	#get the date for the opening

	opening_date = instance.opening.timestamp.date()
	days_diff = todate - opening_date
	days_diff = days_diff.days

	if instance.datebetween is None:
		instance.datebetween = days_diff
		instance.save()

	#saving the new aggregate score to the teachers model
	new_agg_score = instance.teacher.get_score()
	instance.teacher.review_score = new_agg_score
	instance.teacher.save()


post_save.connect(update_review, sender=ReviewTeacher)

src/orderreview/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit, Div, MultiField, Field, Reset
from crispy_forms.bootstrap import TabHolder, Tab, InlineCheckboxes, AppendedText, InlineRadios
from orderreview.models import ReviewTeacher


class OrderCompleteReviewForm(forms.ModelForm):

	class Meta:
		model = ReviewTeacher
		fields = [
			"score",
			"gradebefore",
			"gradeafter",
			"review",
			# "anonymous"

		]

	def __init__(self, *args, **kwargs):
		super(OrderCompleteReviewForm, self).__init__(*args, **kwargs)
		self.fields['score'].label = "Please Rate your Tutor"
		self.fields['score'].help_text = "Please rate with 5 being the best and 1 being the worst experience"
		self.fields['review'].label = "Feedback"
		# self.fields['anonymous'].help_text = "Please tick if you are want to remain anonymous"
		self.helper = FormHelper(self)
		# self.helper.form_method = 'post'
		self.helper.add_input(Submit('submit', value='Submit Review', css_class='buttonspace btn-success'))
		self.helper.layout = Layout(
					# Div(InlineRadios('score'), css_class='col-xs-12 col-md-12 col-lg-12'),
					Div(InlineRadios('gradebefore'), css_class='col-xs-12 col-md-12 col-lg-12'),
					Div(InlineRadios('gradeafter'), css_class='col-xs-12 col-md-12 col-lg-12')
		)

	int_choices = [tuple([x, x]) for x in range(1, 6)]


	grade_choices = (
		('100-95', '100-95'),
		('94-90', '94-90'),
		('89-85', '89-85'),
		('84-80', '84-80'),
		('79-75', '79-75'),
		('74-70', '74-70'),
		('69-65', '69-65'),
		('64-60', '64-60'),
		('59-55', '59-55'),
		('54-50', '54-50'),
		('49-45', '49-45'),
		('45-40', '45-40'),
		('0-39', '0-39'),
	)

	score = forms.ChoiceField(
		# widget=forms.RadioSelect,
		widget=forms.Select,

		choices=int_choices
	)


	gradebefore = forms.ChoiceField(
		widget=forms.RadioSelect,
		choices=grade_choices,
		label="Student grades before tutor engagement",
		required=False
	)

	gradeafter = forms.ChoiceField(
		widget=forms.RadioSelect,
		choices=grade_choices,
		label="Student grades after tutor engagement",
		required=False
	)

class OrderCancelReviewForm(forms.ModelForm):

	class Meta:
		model = ReviewTeacher
		fields = [
			"reason",
			"comments",
		]

	def __init__(self, *args, **kwargs):
		super(OrderCancelReviewForm, self).__init__(*args, **kwargs)
		self.fields['reason'].label = "Reason for cancellation"
		self.helper = FormHelper()
		self.helper.form_method = 'post'
		self.helper.add_input(Submit('submit', value='Submit cancellation', css_class='buttonspace btn-success'))
		self.helper.layout = Layout(
					Div(('reason'), css_class='col-xs-12 col-md-12 col-lg-12')
		)

	reasons = (
		('No response', 'No response from the applicant'),
		('Unable to perform task', 'Applicant is unable to perform task'),
		('Unable to provide documention', 'Applicant is unable to provide valid documention'),
		('Job Canceled', 'Job has been canceled'),
		('Others', 'Other reasons')
	)

	reason = forms.ChoiceField(
		widget=forms.RadioSelect,
		choices=reasons
	)




class ReviewFormComment(forms.ModelForm):

	class Meta:
		model = ReviewTeacher
		fields = [
			"reviewcomment",
		]

	def __init__(self, *args, **kwargs):
		super(ReviewFormComment, self).__init__(*args, **kwargs)
		self.helper = FormHelper()
		self.helper.form_method = 'post'
		self.fields['reviewcomment'].label = "Comment on your review"
		self.helper.add_input(Submit('submit', value='Submit Comment', css_class='buttonspace btn-success'))
		self.helper.layout = Layout(
					Div(('reviewcomment'), css_class='col-xs-12 col-md-12 col-lg-12')
		)

	# reasons = (
	# 	('No response', 'No response from the applicant'),
	# 	('Unable to perform task', 'Applicant is unable to perform task'),
	# 	('Unable to provide documention', 'Applicant is unable to provide valid documention'),
	# 	('Job Canceled', 'Job has been canceled'),
	# 	('Others', 'Other reasons')
	# )

	# reason = forms.ChoiceField(
	# 	widget=forms.RadioSelect,
	# 	choices=reasons
	# )

src/orderreview/templates/review/order_complete_conf.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}


<style>
{% block style %}
/*.jumbotron {
	background-color:#155A1E;
	color:#FFF;

}*/
{% endblock %}
</style>


{% block special %}


<div class="panel panel-default">
<div class="panel-heading">
<h2 class="panel-title msgtitle"><b>Please confirm that you have completed</b></h2>
</div>
<div class="panel-body">

	The opening <b>{{msg.re_opening}}</b> has been completed

<div class='col-sm-10  col-sm-offset-2'>
	<form action='' method="POST" style="display: inline">{% csrf_token %}
	<input class='buttonspace btn btn-success' type="submit" value="Confirm">
	</form>

	<a href='{{ msg.get_absolute_url }}' data-action='show-spinner' class='buttonspace btn btn-primary' >Back to Messages</a>
</div>


</div>


</div>

</div>
</div>


{% endblock %}

src/orderreview/templates/review/order_review.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load staticfiles %}


{% block additional_links %}
     {{ block.super }}
     {% if additionjs %}
         <script type="text/javascript" src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
         <link rel="stylesheet" href="{% static 'css/fontawesome-stars.css' %}">
         <script type="text/javascript" src="{% static 'js/jquery.barrating.min.js' %}"></script>
         <script>
         window.onload = function() {
             $.getScript('/static/js/jquery.barrating.min.js', function()
             {
               $('#id_score').barrating({
                 theme: 'fontawesome-stars'
               });
               $('#id_score').barrating('set', 3);
                 });
         };
         </script>
     {% endif %}
 {% endblock %}
 

<style>
{% block style %}
/*.jumbotron {
	background-color:#155A1E;
	color:#FFF;

}*/
{% endblock %}
</style>


{% block special %}

	<div class="panel panel-default">
	<div class="panel-heading"><h4 class="panel-title"><b>{{ title }}</b></h4></div>
	  <div class="panel-body">

		<br>
		{% crispy form %}

	  </div>
	</div>

{% endblock %}

src/orderreview/templates/review/review_detail.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load staticfiles %}



{% block additional_links %}
 {{ block.super }}
 {% if additionjs %}
     <script type="text/javascript" src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
     <link rel="stylesheet" href="{% static 'js/fontawesome-stars.css' %}">
     <script type="text/javascript" src="{% static 'js/jquery.barrating.min.js' %}"></script>
     <script>
     window.onload = function() {
         $.getScript('/static/js/jquery.barrating.min.js', function()
         {
           $('#id_score').barrating({
             theme: 'fontawesome-stars'
           });
           $('#id_score').barrating('set', 3);
             });
     };
     </script>
 {% endif %}
{% endblock %}


<style>
{% block style %}
/*.jumbotron {
	background-color:#155A1E;
	color:#FFF;

}*/
{% endblock %}
</style>

{% block special %}

<div class="panel panel-default">
<div class="panel-heading">
<h4 class="panel-title"><b>Review</b></h4>
</div>
<div class="panel-body">

	<div class="panel panel-default">
	<div class="panel-heading">
	<h5><b>Review: {{review.opening}}</b></h5>
	</div>
	<div class="panel-body">

			<div class='col-sm-4'>
				<p><b>Details:</b></p>
				<div class="panel panel-default">
				<div class="panel-body">

				<p><b>Subject:</b> {{review.subject}}</p>
				<p><b>Level:</b> {{review.level}}</p>

				<p>
				<b>Grp Tuition:</b>
				{% if review.group_tuition == True %}
				Yes
				{% else %}
				No
				{% endif %}
				</p>

				<p><b>Rate:</b> ${{review.price}}/Hour</p>
				<p><b>Score:</b> {{review.get_rscore}}/5.0</p>
				<p><b>Grades Before:</b> {{review.gradebefore}}</p>
				<p><b>Grades After:</b> {{review.gradeafter}}</p>
				</div>
				</div>
			</div>

			
			<div class='col-sm-8'>

			<p><b>Feedback:</b></p>
			<div class="panel panel-default">
				<div class="panel-body">
				<p> {{review.review}}</p>

				</div>
			</div>

			<p><b>Teacher Comment:</b></p>
			<div class="panel panel-default">
				<div class="panel-body">

				<p> {{review.reviewcomment}}</p>
				</div>
			</div>
			</div>



		<div class="row"></div><br>

			{% if not review.reviewcomment %}
			{% if request.user == review.teacher.user %}
			{% crispy form %}
			{% endif %}
			{% endif %}



	</div>
	</div>



<a href='{{ review.get_message_url }}' class='btn btn-primary buttonspace' >Back to Messages</a>

</div>
</div>




{% endblock %}

src/orderreview/templates/review/review_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}


<style>
{% block style %}
/*.jumbotron {
	background-color:#155A1E;
	color:#FFF;

}*/
{% endblock %}
</style>

{% block special %}

<div class="panel panel-default">
<div class="panel-heading">
<h4 class="panel-title"><b> Reviews for {{ Teacher_Name }} </b></h4>
</div>
<div class="panel-body">

{% if object_list %}

	{% for i in object_list %}

	<div class="panel panel-default">
		<div class="panel-heading">
			<div class='col-sm-6'><h5><b>Review: {{i.opening}}</b></h5></div>
			<small>
			<p align="right">
			Reviewed by:
			{{i.student}}
			</p>
			<p align="right">{{i.timestamp}}</p>
			</small>
		</div>

		<div class="panel-body">

			<div class='col-sm-4'>
				<p><b>Details:</b></p>
				<div class="panel panel-default">
				<div class="panel-body">

				<p><b>Subject:</b> {{i.subject}}</p>
				<p><b>Level:</b> {{i.level}}</p>

				<p>
				<b>Grp Tuition:</b>
				{% if i.group_tuition == True %}
				Yes
				{% else %}
				No
				{% endif %}
				</p>

				<p><b>Rate:</b> ${{i.price}}/Hour</p>
				<p><b>Score:</b> {{i.get_rscore}}/5.0</p>
				<p><b>Grades Before:</b> {{i.gradebefore}}</p>
				<p><b>Grades After:</b> {{i.gradeafter}}</p>
				</div>
				</div>
			</div>

			
			<div class='col-sm-8'>

			<p><b>Feedback:</b></p>
			<div class="panel panel-default">
				<div class="panel-body">
				<p> {{i.review}}</p>

				</div>
			</div>

			<p><b>Teacher Comment:</b></p>
			<div class="panel panel-default">
				<div class="panel-body">

				<p> {{i.reviewcomment}}</p>
				</div>
			</div>

			</div>

		</div>

	</div>

	<div class="row"></div>

	{% endfor %}

{% else %}
<p><b>Teacher has no reviews currently.</b></p>
{% endif %}


<a href='{{ Teacher_Detail_URL }}' class='btn btn-primary buttonspace' >Back to tutor details</a>

</div>
</div>


{% if page_obj.has_previous %}
	<a href='{% url "ReviewList" %}?page={{ page_obj.previous_page_number }}'>Previous</a>
{% endif %}
Page {{ page_obj.number }} of {{ paginator.num_pages }}
{% if page_obj.has_next %}
	<a href='{% url "ReviewList" %}?page={{ page_obj.next_page_number }}'>Next</a>
{% endif %}



{% endblock %}